address = "0.0.0.0"
port = 8000

[log]
level = "trace"
endpoint = "http://grafana-tempo:4317"

[database]
host = "postgres-db"
username = "postgres"
password = "password"
db_name = "newsletter"
migrate = true
